name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, Release and Publish Docker Image
    runs-on: ubuntu-latest
    steps:

# VALIDATE TAGS
    - id: validate-semver
      name: Validate tag against semantic versioning
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        if [[ ! $GITHUB_REF =~ ^refs/tags/v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$ ]]
          then
            echo "Tag $GITHUB_REF does not follow semantic versioning"
            exit 1
          fi

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@v1.4.0
      with:
        java-version: 8

# BUILD FOR DISTRIBUTION
    - id: build-project
      name: Build for distribution
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          clean package

# CREATE GITHUB RELEASE
    - id: create-release
      name: Create GitHub release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          SchemaCrawler ${{ github.event.release.tag_name }} release at last commit ${{ github.sha }}
          See the change history at https://www.schemacrawler.com/changes-report.html
        generate_release_notes: true
        files: ./target/database-connection-test.zip

# BUILD AND PUBLISH DOCKER IMAGE
    - id: setup-qemu
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - id: setup-buildx
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile
        context: .
        platforms: |-
          linux/amd64
          linux/arm64
        tags: |-
          schemacrawler/database-connection-test:v1.0.0
          schemacrawler/database-connection-test:latest
        sbom: true
        provenance: true
        push: true
